on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Add GitHub NuGet source
      run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN_NUGET }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Restore dependencies
      run: dotnet restore ./src/Api.GRRInnovations.StringExtensions.Slugify.csproj

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack ./src/Api.GRRInnovations.StringExtensions.Slugify.csproj --configuration Release --output .

    - name: Push to GitHub Packages
      run: dotnet nuget push *.nupkg --source "github" --skip-duplicate